### ISSUE TITLE
Problems with reading xpose.ini in xpose.data

### ISSUE THREAD

**Issue by MikeKSmith** [andrewhooker/xpose4#3]
Running Xpose-4.5.3 under Windows 8, R-3.2.2. 

In xpose.data there is the following code to pick up xpose.ini:
`xpobj <- new("xpose.data", Runno = 1, Doc = NULL, Data = NULL)

if (is.readable.file("xpose.ini")) {
  xpobj <- xpose.read(xpobj, file = "xpose.ini")
}
else {
  rhome <- R.home()
  xdefini <- paste(rhome, "\\library\\xpose4\\xpose.ini", 
                   sep = "")
  if (is.readable.file(xdefini)) {
    xpobj <- xpose.read(xpobj, file = xdefini)
  }
  else {
    xdefini2 <- paste(rhome, "\\library\\xpose4\\xpose.ini", 
                      sep = "")
    if (is.readable.file(xdefini2)) {
      xpobj <- xpose.read(xpobj, file = xdefini2)
    }
  }
}`

I suspect the definition of `xdefini` should actually point to `.libPaths()[1] ` rather than` R.home()`. In Windows, if R libraries are installed in the user directory ("Documents"), then `.libPaths()` would point to this location as the first entry. `R.home() ` will point to the installation directory of R. It depends where users have their libraries... At present I think the code points to the same location for `xdefini `and `xdefini2`... I think this is a mistake. Perhaps using `.libPaths()[1]` and `.libPaths()[2]` would be more robust? 

Also, I'd suggest that you probably want to look at the user level before proceeding to the installation default.

Regards,
Mike

**Comment by andrewhooker** [comment]
Thanks mike.  Fixed in new release (coming out this week).
